name: Develop Workflow

on:
  push:
    branches:
      - develop
  workflow_call:

jobs:
  lamassu_ca_unit_testing:
    name: CA Unit Testing
    # runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 
      
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run Go Unit Tests
        run: |
          set -eo pipefail
          go test -json -v ./pkg/ca/server/api/service/ | gotestfmt


  lamassu_dms_enroller_unit_testing:
    name: DMS Enroller Unit Testing
    # runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 
      
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run Go Unit Tests
        run: |
          set -eo pipefail
          go test -json -v ./pkg/dms-enroller/server/api/service/ | gotestfmt

  lamassu_device_manager_unit_testing:
    name: Device Manager Unit Testing
    # runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 
      
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run Go Unit Tests
        run: |
          set -eo pipefail
          go test -json -v ./pkg/device-manager/server/api/service/ | gotestfmt