name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  unit_testing_ca:
    name: Unit Testing CA
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run CA unit tests
        uses: ./.github/workflows/ca-develop.yaml

  unit_testing_dms_enroller:
    name: Unit Testing DMS Enroller
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run DMS Enroller unit tests
        uses: ./.github/workflows/dms-enroller-develop.yaml

  unit_testing_device_manager:
    name: Unit Testing Device Manager
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Device Manager unit tests
        uses: ./.github/workflows/device-manager-develop.yaml

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 

  build_ca_dev_docker_image:
      name: CA - Release DEV docker images
      needs:
      - unit_testing_ca
      - unit_testing_dms_enroller
      - unit_testing_device_manager
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      steps:        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build CA DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/ca.dockerfile
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-ca-dev:${{ github.sha }}
            lamassuiot/lamassu-ca-dev:latest
          push: true

  build_device_manager_dev_docker_image:
      name: Device Manager - Release DEV docker images
      needs:
      - unit_testing_ca
      - unit_testing_dms_enroller
      - unit_testing_device_manager
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Device Manager DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/device-manager.dockerfile 
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-device-manager-dev:${{ github.sha }}
            lamassuiot/lamassu-device-manager-dev:latest
          push: true

  build_dms_enroller_dev_docker_image:
      name: DMS Enroller - Release DEV docker images
      needs:
      - unit_testing_ca
      - unit_testing_dms_enroller
      - unit_testing_device_manager
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build DMS Enroller DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/dms-enroller.dockerfile
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-dms-enroller-dev:${{ github.sha }}
            lamassuiot/lamassu-dms-enroller-dev:latest
          push: true

  build_cloud_proxy_dev_docker_image:
      name: Cloud Proxy - Release DEV docker images
      needs:
      - unit_testing_ca
      - unit_testing_dms_enroller
      - unit_testing_device_manager
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Cloud Proxy DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/cloud-proxy.dockerfile 
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-cloud-proxy-dev:${{ github.sha }}
            lamassuiot/lamassu-cloud-proxy-dev:latest
          push: true

  deploy_to_release_env:
      name: Deploy to DEV Server
      needs:
      - build_ca_dev_docker_image
      - build_cloud_proxy_dev_docker_image
      - build_device_manager_dev_docker_image
      - build_dms_enroller_dev_docker_image
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::345876576284:role/LamassuGHActions
          role-session-name: ghactionsrolesession
          aws-region: eu-west-1
      
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.4.1
      
      - name: Install dependencies
        run: npm i -g cdk

      - name: CDK synth
        run: cdk synth

      - name: CDK deploy
        run: cdk deploy --require-approval never --json --outputs-file cdk-outputs.json

      - name: Cat cdk output
        run: cat cdk-outputs.json