name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  unit_testing_ca:
    name: Unit Testing CA
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run CA unit tests
        uses: ./.github/workflows/ca-develop.yaml

  unit_testing_dms_enroller:
    name: Unit Testing DMS Enroller
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run DMS Enroller unit tests
        uses: ./.github/workflows/dms-enroller-develop.yaml

  unit_testing_device_manager:
    name: Unit Testing Device Manager
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Device Manager unit tests
        uses: ./.github/workflows/device-manager-develop.yaml

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 

  build_docker_resources:
      name: Release DEV docker images
      needs:
      - unit_testing_ca
      - unit_testing_dms_enroller
      - unit_testing_device_manager
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      steps:        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build CA DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/ca.dockerfile
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-ca-dev:${{ github.sha }}
            lamassuiot/lamassu-ca-dev:latest
          push: true

      - name: Build Device Manager DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/device-manager.dockerfile 
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-device-manager-dev:${{ github.sha }}
            lamassuiot/lamassu-device-manager-dev:latest
          push: true

      - name: Build DMS Enroller DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/dms-enroller.dockerfile
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-dms-enroller-dev:${{ github.sha }}
            lamassuiot/lamassu-dms-enroller-dev:latest
          push: true

      - name: Build Cloud Proxy DEV docker image
        uses: docker/build-push-action@v2
        with:
          file: ci/cloud-proxy.dockerfile 
          build-args: |
            BASE_IMAGE=alpine:3.14
          tags: |
            lamassuiot/lamassu-cloud-proxy-dev:${{ github.sha }}
            lamassuiot/lamassu-cloud-proxy-dev:latest
          push: true

  deploy_to_release_env:
      name: Deploy to DEV Server
      needs:
      - build_docker_resources
      # runs-on: self-hosted
      runs-on: ubuntu-latest
      environment: release
      steps:              
      - name: Clean previous deployment
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker system prune -a --volumes
          rm -r DEPLOY_PATH/*
      
      - name: "test"
        run: ehco ${{ secrets.DEPLOY_PATH }}

      - name: Clone Lamassu Compose repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/lamassuiot/lamassu-compose
          ref: develop
          path: my-tools
